apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-env-configmap
data:    
  .env: |
    K1="value1"
    K2="value2"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-env-configmap-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: nodejs-env-configmap-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-env-configmap-app
  labels:
    app: nodejs-env-configmap-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-env-configmap-app
  template:
    metadata:
      labels:
        app: nodejs-env-configmap-app
    spec:
      containers:
      - image: docker.io/local/nodejs-env-configmap-service-image:slim    
        name: nodejs-env-configmap-container
        resources: {}
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
            name: nodejs
        volumeMounts:
        - name: config
          mountPath: /usr/src/app/.env
          subPath: .env
      volumes:
        - name: config
          configMap:
            name: nodejs-env-configmap
        